version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: newhk-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongopwd
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./config/mongodb:/data/configdb
      - ./logs/mongodb:/var/log/mongodb
    networks:
      - newhk-network

  api:
    build: .
    container_name: newhk-api
    environment:
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=mongopwd
      - DATABASE_NAME=newhk
    ports:
      - "8111:8000"
    depends_on:
      - mongodb
    networks:
      - newhk-network

networks:
  newhk-network:
    driver: bridge

volumes:
  mongodb_data:
    name: newhk_mongodb_data
