version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: newhk-cursor-ms-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongopwd
    ports:
      - '27017:27017'
    volumes:
      - ./mongodb/database:/data/db
    restart: unless-stopped
